- name: Import Python Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: Open port 8080
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload

