- name: Disable nginx default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx 1.24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy nginx config file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove the nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create the nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download the extract the frontend code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start the nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true

- name: Allow HTTP in firewall
  ansible.builtin.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes