- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: Set root password
  ansible.builtin.command: >
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"
  ignore_errors: true

- name: Remove anonymous users
  ansible.builtin.command: >
    mysql -e "DELETE FROM mysql.user WHERE User='';"
  ignore_errors: true

- name: Disallow root login remotely
  ansible.builtin.command: >
    mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host!='localhost';"
  ignore_errors: true

- name: Remove test database
  ansible.builtin.command: >
    mysql -e "DROP DATABASE IF EXISTS test;"
  ignore_errors: true

- name: Reload privilege tables
  ansible.builtin.command: >
    mysql -e "FLUSH PRIVILEGES;"

- name: Open MySQL port 3306
  ansible.posix.firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
    immediate: yes