- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: Set root password (initial)
  ansible.builtin.command: >
    mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';"
  ignore_errors: true

- name: Secure MySQL - remove anonymous users
  ansible.builtin.command: >
    mysql -uroot -pRoboShop@1 -e "DELETE FROM mysql.user WHERE User='';"

- name: Secure MySQL - disallow root remote login
  ansible.builtin.command: >
    mysql -uroot -pRoboShop@1 -e "DELETE FROM mysql.user WHERE User='root' AND Host!='localhost';"

- name: Remove test DB
  ansible.builtin.command: >
    mysql -uroot -pRoboShop@1 -e "DROP DATABASE IF EXISTS test;"

- name: Flush privileges
  ansible.builtin.command: >
    mysql -uroot -pRoboShop@1 -e "FLUSH PRIVILEGES;"

- name: Open MySQL port
  ansible.posix.firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
    immediate: yes