- name: Copy the Dispatch Service File
  ansible.builtin.copy:
    src: {{ app_name }}.service
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Install Golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Download and extract dispatch code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes

- name: Initialize Go module
  ansible.builtin.command:
    - go mod init dispatch
    - go get
    - go build
  args:
    chdir: /app

- name: Start dispatch service
  ansible.builtin.systemd_service:
    name: dispatch
    state: started
    enabled: yes
    daemon_reload: true