- name: Import NodeJS Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copy Mongodb Repo File
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master Data
  community.mongodb.mongodb_shell:
    login_host: mongodb-{{ ENV }}.azdevopsb82.online
    file: "/app/db/master-data.js"
    idempotent: yes

- name: Open port 8080
  ansible.builtin.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload




