- name: Download Docker repo file
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - python3-pip
    state: present

- name: Start and enable Docker
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    enabled: true

- name: Remove old docker python SDK
  become: true
  ansible.builtin.pip:
    name:
      - docker-py
    state: absent
    executable: pip3
  ignore_errors: true

- name: Install Docker Python SDK
  become: true
  ansible.builtin.pip:
    name:
      - docker==6.1.3
      - requests==2.31.0
      - requests-unixsocket
    executable: pip3

- name: Remove invalid DOCKER_HOST entry
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^DOCKER_HOST='
    state: absent

- name: Set Docker host environment
  become: true
  ansible.builtin.shell: |
    export DOCKER_HOST=unix:///var/run/docker.sock

- name: Verify Docker SDK
  become: true
  ansible.builtin.shell: |
    python3 -c "import docker; client=docker.DockerClient(base_url='unix:///var/run/docker.sock'); print(client.version())"
  register: docker_test

- name: Print Docker SDK result
  ansible.builtin.debug:
    var: docker_test.stdout_lines